//Security Endpoints
### register a user
POST http://{{url}}/auth/register

{
    "username": "user",
    "password": "pass12345"
}


### login
POST http://{{url}}/auth/login

{
    "username": "ADMIN",
    "password": "1234"
}

### test user token
GET http://{{url}}/protected/user_demo
AUTHORIZATION: Bearer {{uToken}}

### test admin token
GET http://{{url}}/protected/admin_demo
AUTHORIZATION: Bearer {{aToken}}


### GET All Candidates
GET https://{{url}}/candidates
AUTHORIZATION: Bearer {{aToken}}

### GET All Candidates sorted by popularity
GET https://{{url}}/candidates/top-by-popularity
AUTHORIZATION: Bearer {{aToken}}

### Get all Candidates with ?category=frontend
GET https://{{url}}/candidates?category=frontend
AUTHORIZATION: Bearer {{aToken}}

### GET With id
GET https://{{url}}/candidates/1
AUTHORIZATION: Bearer {{aToken}}

### POST Candidate
POST https://{{url}}/candidates
Content-Type: application/json
AUTHORIZATION: Bearer {{aToken}}

{
  "name": "Rasmus",
  "phoneNumber": "91919191",
  "educationBackground":"Ek"
}

### Update a candidate
PUT https://{{url}}/candidates/6
Content-Type: application/json
AUTHORIZATION: Bearer {{aToken}}

{
  "name": "Rasmus",
  "phoneNumber": "41414141",
  "educationBackground":"Ek"
}

### Adds a skill to the Candidate
PUT https://{{url}}//candidates/6/skills/1
AUTHORIZATION: Bearer {{aToken}}


### Delete a Candidate
DELETE https://{{url}}/candidates/6
AUTHORIZATION: Bearer {{aToken}}

